version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: dotnet restore
build:
  verbosity: quiet 
test_script:  
   - OpenCover.Console.exe -register:user -target:"dotnet.exe" -targetargs:"test UnitTest.EquationsOfMotion" -output:".\coverage.xml" -filter:"+[EquationsOfMotion]* -[UnitTest*]*" -oldStyle
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml"
